---
title: "What is Happiness, really?"
documentclass: elsarticle
Thesis_FP: no
output:
  pdf_document:
    keep_tex: yes
    template: Tex/TexDefault.txt
    fig_width: 3.5
    fig_height: 3.5
  html_document:
    df_print: paged
Author1: Wesley Williams
Ref1: Stellenbosch University
Email1: 21691126\@sun.ac.za
BottomRFooter: \footnotesize Page \thepage
addtoprule: yes
addfootrule: yes
margin: 2.3
bottom: 2
top: 2.5
HardSet_layout: yes
linenumbers: no
bibliography: Tex/ref.bib
csl: "Tex/harvard-stellenbosch-university.csl"
RemovePreprintSubmittedTo: yes
toc: no
numbersections: yes
fontsize: 11pt
linestretch: 1.2
link-citations: yes
AddTitle: yes
---

<!-- First: Set your default preferences for chunk options: -->

<!-- If you want a chunk's code to be printed, set echo = TRUE. message = FALSE stops R printing ugly package loading details in your final paper too. I also suggest setting warning = FALSE and checking for warnings in R, else you might find ugly warnings in your paper. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')
# Note: Include = FALSE implies the code is executed, but not printed in your pdf.
# warning and message = FALSE implies ugly messages and warnings are removed from your pdf.
# These should be picked up when you execute the command chunks (code sections below) in your rmd, not printed in your paper!

# Lets load in example data, and see how this can be stored and later called from your 'data' folder.
if(!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)

list.files('code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))

happy <- Data_Collating(Datroot = "Data/Happy/")

```


<!-- ############################## -->
<!-- # Start Writing here: -->
<!-- ############################## -->

# Introduction \label{Introduction}

```{r warning =  FALSE, fig.align = 'center', fig.cap = "Plot1.\\label{Figure1}", fig.ext = 'png', fig.height = 5, fig.width = 5}


g <- plotter1(happy)

   g
```

```{r warning =  FALSE, fig.align = 'center', fig.cap = "Plot2.\\label{Figure2}", fig.ext = 'png', fig.height = 5, fig.width = 7}

barplot <- happy %>% 
    group_by(`Regional indicator`) %>% 
    summarise_at((vars(c(starts_with("Explained by"), `Dystopia + residual`, `Ladder score`))), ~median(.))

sabarplot <- happy %>% 
  filter(`Country name` == "South Africa") %>% 
    summarise_at((vars(c(starts_with("Explained by"), `Dystopia + residual`, `Ladder score`))), ~median(.)) 

barplot <- bind_rows(barplot, sabarplot)
barplot[11,1] <- "South Africa"

barplot <- barplot %>% 
    gather(Score, Value, -`Regional indicator`,-`Ladder score`) %>% 
    mutate(Score = gsub("Explained by: ", "", Score))

#need to get the ordering right, South africa and then all of the regions in desending life ladder values\

order1 <- c("South Africa",
            happy %>% group_by(`Regional indicator`) %>% summarise(Lad = mean(`Ladder score`)) %>% arrange(Lad) %>% pull(`Regional indicator`))
order2 <- barplot %>% group_by(Score) %>% summarise(Avg = mean(Value)) %>% arrange(Avg) %>% pull(Score)

g <-
barplot %>%
    plot_orderset(., Column = "Regional indicator", Order = order1) %>%
    plot_orderset(., Column = "Score", Order = order2) %>%
    ggplot() + geom_bar(aes(`Regional indicator`, y = Value, fill = Score), stat = "identity", position = "stack") +
    theme_bw() +
    scale_fill_brewer(palette="Dark2") +
    scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
    labs(title = "Title", subtitle = "Subtitle", caption = "Data source: World Happiness Index", x = "", y = "Breakdown of Happiness") +
    theme(legend.position = "top", legend.title = element_text()) +
    theme(plot.title = element_text(size = 14),
          plot.subtitle = element_text(size = 12), axis.text.x = element_text(size = 10)) +
    guides(fill = guide_legend())

g
```

\newpage

# References {-}

<div id="refs"></div>


# Appendix {-}

## Appendix A {-}

Some appendix information here

## Appendix B {-}

